// Generated by Wrangler by running `wrangler types`

// eslint-disable-next-line @typescript-eslint/no-empty-interface
interface Env {
  DB: D1Database;
  R2_BUCKET: R2Bucket;

  // Environment variables
  APP_ENV: 'development' | 'production';
  SESSION_SECRET: string;
}
