// Generated by Wrangler by running `wrangler types`

// eslint-disable-next-line @typescript-eslint/no-empty-interface
interface Env {
  DB: D1Database;
  R2_BUCKET: R2Bucket;

  // Environment variables
  APP_ENV: 'development' | 'production';
  SESSION_SECRET: string;
  GOOGLE_CLIENT_ID: string;
  GOOGLE_CLIENT_SECRET: string;
  FIREBASE_API_KEY: string;
  FIREBASE_AUTH_DOMAIN: string;
  FIREBASE_PROJECT_ID: string;
  FIREBASE_APP_ID: string;
  FIREBASE_MESSAGING_SENDER_ID: string;
  FIREBASE_MEASUREMENT_ID: string;
  FIREBASE_STORAGE_BUCKET: string;
}
